apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/gregorytereshko/goit-argo.git
    path: namespaces/application
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true