apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: infra-tools
spec:
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.min.io
    chart: minio
    targetRevision: 5.3.0
    helm:
      valuesObject:
        replicas: 1
        mode: standalone
        rootUser: minio
        rootPassword: minio123
        buckets:
          - name: mlflow-artifacts
            policy: none
            purge: false
        service:
          type: ClusterIP
        persistence:
          enabled: false
        resources:
          requests:
            memory: 512Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true