apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: minio
 namespace: infra-tools
spec:
 destination:
  namespace: application
  server: https://kubernetes.default.svc
 project: default
 source:
  repoURL: https://charts.bitnami.com/bitnami
  chart: minio
  targetRevision: 13.7.2
  helm:
   valuesObject:
    image:
      repository: minio/minio
      tag: RELEASE.2025-09-07T16-13-09Z-cpuv1
    auth:
     rootUser: minio
     rootPassword: minio123
    defaultBuckets: "mlflow-artifacts"
    service:
     type: ClusterIP
    persistence:
     enabled: false
 syncPolicy:
  automated:
   prune: true
   selfHeal: true
  syncOptions:
   - CreateNamespace=true
   - ServerSideApply=true
   - SkipDryRunOnMissingResource=true
