apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: mlflow-postgres
 namespace: infra-tools
spec:
 destination:
  namespace: application
  server: https://kubernetes.default.svc
 project: default
 source:
  repoURL: https://charts.bitnami.com/bitnami
  chart: postgresql
  targetRevision: 12.5.6
  helm:
   valuesObject:
    image:
      repository: bitnamilegacy/postgresql
      digest: sha256:9c8137a169ccb1f4946137736fbfffd091f6ce9c95c1f504bd7c996e9938a4be
    auth:
     username: mlflow
     password: mlflowpass
     database: mlflow
    primary:
     persistence:
      enabled: false
 syncPolicy:
  automated:
   prune: true
   selfHeal: true
  syncOptions:
   - CreateNamespace=true
   - ServerSideApply=true
   - SkipDryRunOnMissingResource=true
