apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway
  namespace: infra-tools
spec:
  project: default
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-pushgateway
    targetRevision: 2.5.0
    helm:
      valuesObject:
        service:
          type: LoadBalancer
          port: 9091
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true