apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-pushgateway
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-pushgateway
    targetRevision: 2.5.0  # Перевір актуальну версію за потреби
    helm:
      valuesObject:
        service:
          type: ClusterIP
          port: 9091
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Replace=true